name: tweet

on:
  schedule:
    - cron: '0 * * * *' # (00:00, 01:00, 02:00...)

env:
  OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
  TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
  TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
  TWITTER_REDIRECT_URI: ${{ secrets.TWITTER_REDIRECT_URI }}
  FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
  FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python3 main.py